### ISSUE TITLE
No route matches, using url_for to change locale

### ISSUE THREAD

**Issue by Frexuz** [enriclluelles/route_translator#103]
Example, language selector in the footer: 

Lets say my current url is: `/en/pages/contact`,
and i need a link to `/fr/pages/contact`. (Same page, different locale)

I've tried using `url_for` without success:

```
<% I18n.available_locales.each do |language| %>
  <%= link_to(language, url_for(params.merge(locale: language))%>
<% end %>
```

Error: `No route matches {:action=>"show", :controller=>"pages", :locale=>:fr, :page=>"contact"}`

My route
```
localized do
    get '/pages/:page' => 'pages#show', :as => 'pages'
end
```

PS:
I don't really want a custom helper that is replacing strings,
or route to an action, setting the locale and redirecting `:back`

**Comment by tagliala** [comment]
AFAIK This is not going to work, this gem can't help. I'm using a custom solution

**Comment by AlbertoValenzuela** [comment]
Have the same problem.

Is there a way to do it in a clean way? To avoid the dirty way that @Frexuz said at the end.

**Comment by pkuczynski** [comment]
+1

**Comment by pkuczynski** [comment]
#96 is other variant of the same problem

**Comment by pkuczynski** [comment]
This would work however you need to convert locale to string. I recommend also adding `only_path` parameter. So correct way of doing it would be:

```ruby
<% I18n.available_locales.each do |language| %>
  <%= link_to(language, url_for(locale: language.to_s, only_path: true)%>
<% end %>
```

**Comment by pzin** [comment]
I am using it so, which works very nice:

    - I18n.available_locales.each do |locale|
      = link_to locale, locale: locale.to_s

**Comment by jethroo** [comment]
@pkuczynski thx a lot, stumbled over the same issue ;)

**Comment by tagliala** [comment]
https://github.com/enriclluelles/route_translator/wiki/Generating-translated-URLs
