### ISSUE TITLE
undefined method disable_fallback

### ISSUE THREAD

**Issue by alexanderkustov** [enriclluelles/route_translator#111]
Trying to implemenet in my project, setting my initializer

    RouteTranslator.config do |config|
      config.hide_locale = true
      config.disable_fallback = true
    end

 always returns:

NoMethodError: undefined method `disable_fallback=' for #<RouteTranslator::Configuration:0x00000007177288>

**Comment by rmascarenhas** [comment]
That seems to be an issue with the documentation, since [there's no such configuration option](https://github.com/enriclluelles/route_translator/blob/master/lib/route_translator.rb#L12-L15)

**Comment by alexanderkustov** [comment]
Thanks @rmascarenhas for stepping it, actually I solved this by forking this and instead of using an old rubygems version, using it straight from github.

The rubygems version is outdated... @enriclluelles please update it since it breaks quite a major, or put somewhere in the docs, to allow people to build this gem from github instead of rubygems.

**Comment by tagliala** [comment]
Just released 4.1.0

Closing here
