### ISSUE TITLE
Rails 5.0 compatibility

### ISSUE THREAD

**Issue by tagliala** [enriclluelles/route_translator#122]
Rails 5.0 will not work out of the box

https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/routing/mapper.rb#L1665
https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/routing/route_set.rb#L494

https://github.com/enriclluelles/route_translator/tree/feature/rails5

Feel free to make PRs against the above branch
# TODO
- [ ] Possible regression: https://github.com/enriclluelles/route_translator/issues/122#issuecomment-172572085
- [x] Failing seed 3584
- [x] Parial caching #134
- [x] Failing seed 38197

**Comment by tagliala** [comment]
https://github.com/rails/rails/commit/5ba6966766e67af4ae0028c4429acbd280a100a2

**Comment by tagliala** [comment]
3 tests to go

```
  1) Failure:
GeneratedPathTest#test_with_optionals [test/integration/generated_path_test.rb:43]:
expected tag, but no tag found matching {:tag=>"a", :attributes=>{:href=>"/optional/12"}} in:
"<a href=\"/optional/12\">Optional [en]</a>\n"


  2) Failure:
GeneratedPathTest#test_with_prefixed_optionals [test/integration/generated_path_test.rb:53]:
Expected response to be a <success>, but was a <404>


  3) Failure:
TranslateRoutesTest#test_dont_add_locale_to_routes_if_local_param_present [test/routing_test.rb:467]:
The generated path </segment/es/products/product_slug> did not match </segment/es/productos/product_slug>.
--- expected
+++ actual
@@ -1 +1 @@
-"/segment/es/productos/product_slug"
+"/segment/es/products/product_slug"


69 runs, 381 assertions, 3 failures, 0 errors, 0 skips
```

**Comment by tagliala** [comment]
2 tests to go

```
  1) Failure:
TranslateRoutesTest#test_dont_add_locale_to_routes_if_local_param_present [test/routing_test.rb:467]:
The generated path </segment/es/products/product_slug> did not match </segment/es/productos/product_slug>.
--- expected
+++ actual
@@ -1 +1 @@
-"/segment/es/productos/product_slug"
+"/segment/es/products/product_slug"



  2) Failure:
GeneratedPathTest#test_with_prefixed_optionals [test/integration/generated_path_test.rb:53]:
Expected response to be a <success>, but was a <404>

69 runs, 381 assertions, 2 failures, 0 errors, 0 skips
```

Difference of generated routes in `test_with_prefixed_optionals`
Rails 4
```
optional_es (?-mix:^GET$) /es/optional(/:page)(.:format) {:controller=>"dummy", :action=>"optional", :locale=>"es"}
optional_ru (?-mix:^GET$) /ru/optional(/:page)(.:format) {:controller=>"dummy", :action=>"optional", :locale=>"ru"}
optional_en (?-mix:^GET$) /optional(/:page)(.:format)    {:controller=>"dummy", :action=>"optional", :locale=>"en"}
```

Rails 5
```
prefixed_optional_es GET /es/prefixed_optional(/p-:page)(.:format) {:locale=>"es", :controller=>"dummy", :action=>"prefixed_optional"}
prefixed_optional_ru GET /ru/prefixed_optional(/p-:page)(.:format) {:locale=>"ru", :controller=>"dummy", :action=>"prefixed_optional"}
prefixed_optional_en GET /prefixed_optional(/p-:page)(.:format)    {:locale=>"en", :controller=>"dummy", :action=>"prefixed_optional"}
```

**Comment by tagliala** [comment]
https://github.com/rails/rails/issues/23069

**Comment by tagliala** [comment]
Possible regression

#### Routes
```rb
localized do
  resources :products, only: :show
end
```

### config
```rb
RouteTranslator.config.host_locales = {
  'es.lvh.me' => :es,
  'en.lvh.me' => :en
}
```

Rails 4.2.5's rake routes:
```
           Prefix Verb URI Pattern                 Controller#Action
       product_es GET  /es/productos/:id(.:format) products#show {:locale=>"es"}
product_native_es GET  /productos/:id(.:format)    products#show {:locale=>"native_es"}
product_native_en GET  /products/:id(.:format)     products#show {:locale=>"native_en"}
       product_en GET  /products/:id(.:format)     products#show {:locale=>"en"}
```

Rails 5.0.0.beta1's rake routes:
```
           Prefix Verb URI Pattern                 Controller#Action
       product_es GET  /es/productos/:id(.:format) products#show {:locale=>"es"}
product_native_es GET  /productos/:id(.:format)    products#show {:locale=>"es"}
product_native_en GET  /products/:id(.:format)     products#show {:locale=>"en"}
       product_en GET  /products/:id(.:format)     products#show {:locale=>"en"}
```

"native_*" got swallowed up somewhere.

I was attempting to take a look at #87

@danschultzer what do you think about this? Is this a buggy behaviour in both Rails 4 and Rails 5?

**Comment by tagliala** [comment]
Error with seed 22065. Does not happen on master branch

``
$ rake test SEED=22065
  2) Failure:
TranslateRoutesTest#test_action_controller_test_case_reads_default_urls [~/dev/route_translator/test/routing_test.rb:609]:
Failed assertion, no message given.
```

It seems it doesn't add `people_*_path` to test class

**Comment by tagliala** [comment]
Rails 5.0.0.beta2 fixes rails/rails#23069

We have a possible regression and a failing test case with SEED=22065

**Comment by danschultzer** [comment]
> @danschultzer what do you think about this? Is this a buggy behaviour in both Rails 4 and Rails 5?

Sorry, I've had a lot of travel these weeks so first had the time to look at it now. I've had no problems in production despite the duplicate route, but I'm not well-versed in rails routing so not sure if there's any issues in rails 4 having duplicate routes (after all, it's just the path, the rails 5 routes definitely are more of an issue with the native locale missing).

Would love to help you out, I'll see if later I can spin up rails 5 and take a look.

**Comment by tagliala** [comment]
Moved the test case tests in their own file, so we can reproduce the failing test every time by running it in isolation, both on rails5 and master branch

https://github.com/enriclluelles/route_translator/commit/cafe32b9f776732e9023731ced3275b7c75f2f31

The issue is that inflections are not working properly. Maybe they are still not "included"?

Sorry but I'm still not enough skilled to understand this issue

```
=> 49:     assert test_case.respond_to?(:people_path)
   50:     assert test_case.respond_to?(:new_person_path)
   51: 
   52:     # Localized
   53:     assert test_case.respond_to?(:people_en_path)
(byebug) test_case.respond_to? :people_path
false
(byebug) test_case.respond_to? :person_index_path
true
```

**Comment by tagliala** [comment]
Found the obvious reason of the failure

```rb
  resources :person
```

:)

**Comment by danschultzer** [comment]
Hah, that can drive any person crazy. Excellent work, works as expected here :+1: :smile:

**Comment by vizo** [comment]
Is it now compatible with beta3?

**Comment by tagliala** [comment]
Since this gem is compatible and working for rails 5, I will close this but I need to start a new issue because of https://github.com/enriclluelles/route_translator/issues/122#issuecomment-172572085
