### ISSUE TITLE
Linking to an engine mounted inside a localized block fails

### ISSUE THREAD

**Issue by robotex82** [enriclluelles/route_translator#123]
When trying to link to an engine, that is mounted inside a localized block, I get following error message:

```
undefined method `segment_keys' for nil:NilClass
```

I added a failing test for this situation in my fork in the branch engine-in-localized-block (https://github.com/robotex82/route_translator/tree/engine-in-localized-block).

Can you please help?

Thanks in advance!

Best regards
Roberto

**Comment by tagliala** [comment]
I've also seen a fix

Do you mind to submit a PR?

**Comment by robotex82** [comment]
Sorry, I haven't found a fix by now. Should I PR the failing test?

**Comment by tagliala** [comment]
No, don't worry

Since I don't use the gem this way, I'm asking what is the expected behaviour.

I mean, if I mount an engine in a `localized` block, what it should happen?

**Comment by robotex82** [comment]
Mounting works, but when you try to use url_for or a polymorphic route helper on the engine (i.e. blorgh.posts_path) it throws an error (see my first post).

**Comment by robotex82** [comment]
The error ist thrown in https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_dispatch/routing/mapper.rb

In following method:

          def define_generate_prefix(app, name)
            _route = @set.named_routes.get name
            _routes = @set
            app.routes.define_mounted_helper(name)
            app.routes.extend Module.new {
              def optimize_routes_generation?; false; end
              define_method :find_script_name do |options|
                if options.key? :script_name
                  super(options)
                else
                  prefix_options = options.slice(*_route.segment_keys)
                  prefix_options[:relative_url_root] = ''.freeze
                  # we must actually delete prefix segment keys to avoid passing them to next url_for
                  _route.segment_keys.each { |k| options.delete(k) }
                  _routes.url_helpers.send("#{name}_path", prefix_options)
                end
              end
            }
          end

In following line, *_route is nil, and it should not be:

    prefix_options = options.slice(*_route.segment_keys)
