### ISSUE TITLE
More flexible locale parameter handling

### ISSUE THREAD

**Issue by pineapplethief** [enriclluelles/route_translator#129]
I have an app where client wants to have multiple locales per each country, so i have such a scope in most of the routes:

```
scope "(:territory-:locale)", constraints: { territory: /[a-z]{2}/, locale: /[A-Z]{2}/ } do
```

so much locale is more like `/lv-RU/`, `/lv-EN/`, `/lv-LV/`, etc.
It does not work nicely with this gem, since localized routes are prepended just by locale `/ru/`, `/en/`, etc.
Any thoughts on how I could patch your gem to make it work?

**Comment by pineapplethief** [comment]
I worked around this limitation by
a) turning on hide_locale option in RouteTranslator.
b) using excellent [routing_filter](https://github.com/svenfuchs/routing-filter/) gem to add locale and territory to url_for options in a transparent way to get the generated urls right.
But still, I think route_translator tries to do too much and should be more locale-parameter agnostic, so to speak.

**Comment by dholdren** [comment]
Locale can contain language and region using the following format:
`<ISO 2-char language>-<ISO 2-char region, all caps>` i.e.
`de-DE` (German language in Germany)
`de-CH` (German language in Switzerland)
`fr-CH` (French language in Switzerland)
`fr-FR` (French language in France)

I think what you want is:
`ru-LV, en-LV, lv-LV`
If those are in your Rails' `config.i18n.available_locales` and you have i18n ymls for them, it should all work.  You shouldn't need the scope.

**Comment by tagliala** [comment]
Does #138 address this one?

**Comment by tagliala** [comment]
Assuming that #138 fixes this.

Closing here
