### ISSUE TITLE
prefix for translations

### ISSUE THREAD

**Issue by astropanic** [enriclluelles/route_translator#135]
When my routes config has:

``` ruby
scope(path: 'namespace') do
  localized do
    resources :job_titles, only: [:show]
  end
end
```

I get following routes:

```
job_title_en GET  /en/namespace/job_titles/:id(.:format)            job_titles#show {:locale=>"en"}
job_title_de GET  /de/namespace/job_titles/:id(.:format)            job_titles#show {:locale=>"de"}
```

I need the namespace in front of the language, something like:

```
/namespace/en/job_titles/:id(.:format)
/namespace/de/job_titles/:id(.:format)
```

Is it possible with this gem ?

**Comment by tagliala** [comment]
Hi, sorry for the extremely late reply, but I suppose you already understood that at the moment it is not possible.

I'm leaving this open and a PR is very welcome

**Comment by tagliala** [comment]
This should be possible by using the following approach:

https://github.com/enriclluelles/route_translator/blob/master/README.md#change-locale-parameter-position-in-the-path

```rb
Rails.application.routes.draw do
  scope('namespace/:locale') do
    localized do
      resources :job_titles, only: [:show]
    end
  end
end
```
