### ISSUE TITLE
Deprecations for Rails 5

### ISSUE THREAD

**Issue by air720boarder** [enriclluelles/route_translator#141]
DEPRECATION WARNING: around_filter is deprecated and will be removed in Rails 5.1. Use around_action instead. (called from block in <module:Controller> at /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/route_translator-77c8f1f5a990/lib/route_translator/extensions/action_controller.rb:9)

**Comment by tagliala** [comment]
Thanks. Feel free to use the `rails5` branch

Closing here

Ref: #122
