### ISSUE TITLE
Can't link to other locales?

### ISSUE THREAD

**Issue by jan** [enriclluelles/route_translator#142]
In my footer, I want to link to all other localized versions of the current page like so:

    I18n.available_locales.each do |other_locale|
      li= link_to(other_locale, locale: other_locale)

I get the error

    No route matches {:action=>"show", :controller=>"categories", :country=>"de", :locale=>:en, :slug=>"küche-haushalt"}

Although the route seems to match:

         Prefix Verb URI Pattern                                            Controller#Action
    category_en GET  /en/list/category/germany/*slug(.:format)     categories#show {:locale=>"en", :country=>"de"}
    category_de GET  /de/liste/kategorie/deutschland/*slug(.:format) categories#show {:locale=>"de", :country=>"de"}

My routes are build like this:

    localized do
      ["de"].each do |country|
        get "list/category/#{country}/*slug" => 'categories#show', as: :category, country: country
      end
    end

**Comment by guapolo** [comment]
@jan just ran last night into the same issue! :)

Using your example, the fix is to convert `other_locale` into a `String`:

    I18n.available_locales.each do |other_locale|
       li= link_to(other_locale, locale: other_locale.to_s)

**Comment by tagliala** [comment]
Unfortunately this is not so simple, expecially for slugs

Please refer to the wiki page linked by @guapolo

**Comment by tagliala** [comment]
I'm sharing an approach to translate routes, please take a look:

https://github.com/tagliala/route_translator-test/commit/0b5755f19368c54d17cde87c6f68f5bd91a2769a

Maybe there is room for improvement, let me know

application_controller.rb
```rb
  helper_method :localized_url_for

  def localized_url_for
    Proc.new do |locale|
      url_for(only_path: true, locale: locale.to_s)
    end
  end
```

articles_controller.rb
```rb
  def localized_url_for
    case action_name
    when 'show'
      Proc.new do |locale|
        I18n.with_locale(locale) do
          article_path(@article)
        end
      end
    else super
    end
  end
```

_localized_urls.html.erb
```erb
<dl>
  <% I18n.available_locales.each do |locale| %>
    <dt><%= locale.to_s %></dt>
    <dd><%= link_to localized_url_for.call(locale), localized_url_for.call(locale) %></dd>
  <% end %>
</dl>
```
