### ISSUE TITLE
Help with wrapping please - autocomplete_tag_name

### ISSUE THREAD

**Issue by bodaonline** [enriclluelles/route_translator#144]
Hi!

Could someone please help me wrap these. No idea what I am doing, beginner here. :)

    resources :events do
     get :autocomplete_tag_name, :on => :collection
     get :autocomplete_cit_name, :on => :collection
     get "search", :on => :collection
    end
  
    resources :tags
     get 'tags/autocomplete_tag_name'

Tried these but no luck:

    localized do
     resources :events 
      get :autocomplete_tag_name, :on => :collection
      get :autocomplete_cit_name, :on => :collection
      get "search", :on => :collection
    end

    localized do
     resources :tags
      get 'tags/autocomplete_tag_name'
    end

Error is:
/routing/mapper.rb:1390:in `collection': can't use collection outside resource(s) scope (ArgumentError)

**Comment by tagliala** [comment]
Is this issue related to route_translator?

Please take another look at our contributing guidelines to report bugs: https://github.com/enriclluelles/route_translator/blob/master/CONTRIBUTING.md#reporting-issues

**Comment by bodaonline** [comment]
It is relaated to route_translater deffinitely, so much I can tell. :) I also indicated in the title that its a help request not a bug but can't change the tag, not enough rights.

**Comment by tagliala** [comment]
Please provide me an application which works without route_translator and does not work when adding the `localized` block

**Comment by bodaonline** [comment]
OMG... OK... that will take some time but thanks

**Comment by tagliala** [comment]
it should be a new rails application hosted on github and a step-by-step guide to reproduce your issue. You can start with this one: https://github.com/tagliala/route_translator-test

**Comment by bodaonline** [comment]
solved it:

    localized do
    resources :events do
     get :autocomplete_tag_name, :on => :collection
     get :autocomplete_cit_name, :on => :collection
     get "search", :on => :collection
    end
    end

**Comment by tagliala** [comment]
glad you solved, closing here
