### ISSUE TITLE
Deprecation warning arround_filter in rails 5

### ISSUE THREAD

**Issue by kaluznyo** [enriclluelles/route_translator#149]
The around_filter in https://github.com/enriclluelles/route_translator/blob/master/lib/route_translator/extensions/action_controller.rb#L9 raise a warning in rails 5 .

DEPRECATION WARNING: around_filter is deprecated and will be removed in Rails 5.1. Use around_action instead.

Just use around_action instead should fix this

**Comment by tagliala** [comment]
Thanks!

route_translator 5.0.2 released

Surprisingly, I had updated the README with `around_action` but I've forgot the ruby file 😅
