### ISSUE TITLE
disable_fallback = true not working?

### ISSUE THREAD

**Issue by thomey** [enriclluelles/route_translator#153]
Even with `disable_fallback = true`, the gem seems to be generating localized routes for locales and routes that don't have a translation, even in development.

Tried explicitly setting `config.i18n.fallbacks = false` but the behavior is the same...

Rails version: 5.0.0.1
Gem version: 5.0.4

routes.rb:
```ruby
localized do
  get :presentation, to: 'shared/products#show'
end
```

config/initializers/route_translator.rb:
```ruby
RouteTranslator.config do |config|
  config.hide_locale = true
  config.disable_fallback = true
end
```

`rails routes` output (shortened):
...

>   presentation_rm GET    /translation%20missing:%20rm.routes.presentation(.:format)     shared/products#show {:locale=>"rm"}
>     presentation_ro GET    /translation%20missing:%20ro.routes.presentation(.:format)     shared/products#show {:locale=>"ro"}
>     presentation_ru GET    /translation%20missing:%20ru.routes.presentation(.:format)     shared/products#show {:locale=>"ru"}
>     presentation_sk GET    /translation%20missing:%20sk.routes.presentation(.:format)     shared/products#show {:locale=>"sk"}
>     presentation_sl GET    /translation%20missing:%20sl.routes.presentation(.:format)     shared/products#show {:locale=>"sl"}
>     presentation_sq GET    /translation%20missing:%20sq.routes.presentation(.:format)     shared/products#show {:locale=>"sq"}
>     presentation_sr GET    /translation%20missing:%20sr.routes.presentation(.:format)     shared/products#show {:locale=>"sr"}
>  presentation_sv_se GET    /translation%20missing:%20sv-SE.routes.presentation(.:format)  shared/products#show {:locale=>"sv-SE"}
>     presentation_sv GET    /translation%20missing:%20sv.routes.presentation(.:format)     shared/products#show {:locale=>"sv"}
>     presentation_sw GET    /translation%20missing:%20sw.routes.presentation(.:format)     shared/products#show {:locale=>"sw"}
>     presentation_ta GET    /translation%20missing:%20ta.routes.presentation(.:format)     shared/products#show {:locale=>"ta"}
>     presentation_th GET    /translation%20missing:%20th.routes.presentation(.:format)     shared/products#show {:locale=>"th"}
>     presentation_tl GET    /translation%20missing:%20tl.routes.presentation(.:format)     shared/products#show {:locale=>"tl"}
>     presentation_tr GET    /translation%20missing:%20tr.routes.presentation(.:format)     shared/products#show {:locale=>"tr"}
>     presentation_tt GET    /translation%20missing:%20tt.routes.presentation(.:format)     shared/products#show {:locale=>"tt"}

...

**Comment by tagliala** [comment]
@thomey sorry for the late reply. Could you please provide a sample application which shows the issue for faster debugging?

**Comment by thomey** [comment]
Sure: [Sample](https://github.com/thomey/route_translator_bug.git)

Actually, when making the sample I found that the issue is caused by also having the gem [`rails-i18n`](https://github.com/svenfuchs/rails-i18n.git), which seems a bit obvious now in retrospect ;)

Since the gem includes a whole bunch of locales, route_translator detects them as present and generates routes for them, even though they don't actually have a translation for that particular route.

Would it make more sense if disable_fallback also removed routes with missing translation?

**Comment by tagliala** [comment]
Yes, we could do that. But I don't know how 🤔 

You mean: if we have a locale file but that locale file doesn't contain `routes:` consider it as an empty locale? 

Btw give a try to this option from the README

```
available_locales Use this to limit the locales for which URLs should be generated for. Accepts an array of strings or symbols.
```

**Comment by thomey** [comment]
Yeah, that's what I wound up doing meanwhile, but it would be nicer not having to specify them. ;)

Also, routes with a missing translation probably wouldn't work anyway, right? For example `/translation%20missing:%20pl.routes.presentation(.:format)`

You could consider it empty if it didn't have `routes:`, but even better would be to catch if it has a key/value for that specific route, in case you only miss a translation for a specific route in that locale?

**Comment by tagliala** [comment]
IMHO excluding languages basing on the presence/absence of `routes` key in the locale file violates the principle of least surprise, so I would keep using the `available_locales` override.

I'm going to close this one, but if I'm missing something please leave a comment
