### ISSUE TITLE
Locale not set automatically

### ISSUE THREAD

**Issue by pinzonjulian** [enriclluelles/route_translator#160]
Hi! The docs say:

>Your I18n.locale will be set up automatically from the url param when it's available.
>To disable it add this to your controller:
```
skip_around_action :set_locale_from_url
```
However it isn't happening for me. I had to place this in my application_controller.rb
```
around_action :set_locale_from_url
```

I created an initializer called route_translator.rb where I placed the following code:
```
RouteTranslator.config do |config|
  config.available_locales = [:es, :en]
end
```
I'm I missing something?
> ruby version: 2.3.3
> rails version: 5.0.1

Thanks!

**Comment by tagliala** [comment]
Hi,

thanks for reporting this.

Debugging issues is a time consuming task and, without a reduced test case, it is even worse.

If you want me to take a deeper look at this issue, please start a new rails application, commit the minimum amount of code and gems needed to show the issue, push to github and share the repo here

Contributing guidelines
https://github.com/enriclluelles/route_translator/blob/master/CONTRIBUTING.md#reporting-issues

**Comment by tagliala** [comment]
Hi again,

I'm going to close this one

FWIW, Route Translator autoloads its module in `ActionController::Base` here: https://github.com/enriclluelles/route_translator/blob/master/lib/route_translator/extensions/action_controller.rb#L44

So please check that your Application controller is inheriting from `ActionController::Base`
