### ISSUE TITLE
Rails 5.1.0.rc1 add_route wrong number of arguments

### ISSUE THREAD

**Issue by kaluznyo** [enriclluelles/route_translator#163]
Hi, I try to upgrade my project to rails 5.1.0.rc1 and I get this error on startup 

`/Users/olivier/.rvm/gems/ruby-2.4.0/gems/actionpack-5.1.0.rc1/lib/action_dispatch/routing/route_set.rb:576:in `add_route': wrong number of arguments (given 4, expected 2) (ArgumentError)
	from /Users/olivier/.rvm/gems/ruby-2.4.0/gems/route_translator-5.2.1/lib/route_translator/extensions/route_set.rb:14:in `block in add_localized_route'
	from /Users/olivier/.rvm/gems/ruby-2.4.0/gems/route_translator-5.2.1/lib/route_translator/translator.rb:73:in `block in translations_for'
	from /Users/olivier/.rvm/gems/ruby-2.4.0/gems/route_translator-5.2.1/lib/route_translator/translator.rb:65:in `each'
	from /Users/olivier/.rvm/gems/ruby-2.4.0/gems/route_translator-5.2.1/lib/route_translator/translator.rb:65:in `translations_for'
	from /Users/olivier/.rvm/gems/ruby-2.4.0/gems/route_translator-5.2.1/lib/route_translator/extensions/route_set.rb:10:in `add_localized_route'
	from /Users/olivier/.rvm/gems/ruby-2.4.0/gems/route_translator-5.2.1/lib/route_translator/extensions/mapper.rb:40:in `add_route'`

I use route_translator 5.2.1

**Comment by tagliala** [comment]
Hi,

thanks for reporting this.

I can confirm. The first step is lock the maximum rails version to 5.1.0.beta1, yank route_translator 5.2.0 and 5.2.1 and release a 5.2.2.

Then I will try to update this gem to 5.1.0.rc1
