### ISSUE TITLE
Support Rails 5.1.0.rc2

### ISSUE THREAD

**Issue by kaluznyo** [enriclluelles/route_translator#164]
Hi, Rails 5.1.0.rc2 is out, and dependencies seem to blocked to 5.1.0.rc1

**Comment by tagliala** [comment]
Hi,

thanks for reporting this.

I will relax the rails dependency to `< 5.2` and if something goes wrong I will yank gems and release hotfixes

**Comment by tagliala** [comment]
Done in 5.4.0
