### ISSUE TITLE
Check if current page has localized route

### ISSUE THREAD

**Issue by erikdahlstrand** [enriclluelles/route_translator#165]
Hi,

I would like to generate hreflang link tags but only if the current page has localized routes (I'm not localizing all the routes). Is there a way to check this in the view?

Currently I'm generating link tags on all pages, even if the current page doesn't have localized routes.

```ruby
- Rails.configuration.complete_locales.each do |locale|
  link rel='alternate' hreflang=locale href=url_for(locale: locale.to_s, only_path: false)
```

**Comment by tagliala** [comment]
Hi,

This should not be possible. You should provide custom per-page configuration.

I mean, `Rails.configuration.complete_locales` should become something like `@current_page_locales`

Hope it helps
