### ISSUE TITLE
_path helper ignores locale as argument

### ISSUE THREAD

**Issue by adrian282** [enriclluelles/route_translator#170]
Rake routes:
 page_en GET  /en/pages/:id(.:format)                          pages#show {:locale=>"en"}
 page_pl GET  /strony/:id(.:format)                            pages#show {:locale=>"pl"}

**_path** helper creates link always with current locale (parameter :locale is ignored)
page_path(@page, :locale => 'en')    
page_path(@page, :locale => 'pl')

**url_for** working properly (with :locale as argument), but I need _path and _url helpers.

**Comment by tagliala** [comment]
Hi,

please take a look here: https://github.com/enriclluelles/route_translator/wiki/Generating-translated-URLs

You could also go for 

```rb
I18n.available_locales.each do |locale|
  I18n.with_locale(locale) do
    page_path(@page)
  end
end
```

Hope it helps

**Comment by adrian282** [comment]
in general **url_for** is OK, but in this case each page contains unique slug, so I need pass object to **page_path** helper.
Your workaround is OK!
Or another ugly workaround:  url = send('page_%s_path' % [locale], page)

**Comment by tagliala** [comment]
Another solution:
```erb
<% I18n.available_locales.each do |locale| %>
  <%= I18n.with_locale(locale) { link_to url_for(@article), url_for(@article) } %>
<% end %>
```

**Comment by adrian282** [comment]
Thanks. Your first solution working perfectly

**Comment by jaswinder97** [comment]
@tagliala I was not able to build another locale route over a view rendered with a different locale. It always use the initialized locale for a current route on the same view. As per your solution we are not only passing the current locale to the view links but also reinitialize I18n locale at the same time and it works perfectly!! Thanks
