### ISSUE TITLE
Routing parameter at the front

### ISSUE THREAD

**Issue by kkak10** [enriclluelles/route_translator#186]
When my routes config has:
```ruby
Rails.application.routes.draw do
  localized do
    match '/:val/test' => 'test#index', :via => :get
  end
end
```

controller:
```ruby
def index
  param_val = params[:val]
  ...
end
```
I would like to receive a `param_val` as 'hihi' when requested by /en/hihi/test

but `param_val` is 'en'.

How can we fix it?

**Comment by tagliala** [comment]
Hi, 

sorry for the late reply

Does

```
Rails.application.routes.draw do
  scope(':locale') do
    localized do
      match '/:val/test' => 'test#index', :via => :get
    end
  end
end
```

work for your use case?

**Comment by kkak10** [comment]
@tagliala Thanks for the reply. I'll try

**Comment by tagliala** [comment]
Closing here, feel free to comment if it does not solve your issue
