### ISSUE TITLE
Rails 6 support

### ISSUE THREAD

**Issue by jockee** [enriclluelles/route_translator#188]
The Rails 6.0.0 beta1 was just released. Unsure whether routing was substantially.

Thanks for a great gem!

**Comment by tagliala** [comment]
Thanks for the heads-up.

Forunately, I was testing this gem against rails-edge so it has been an easy upgrade.

Waiting for [this build](https://travis-ci.org/enriclluelles/route_translator/builds/481746267) to pass before pushing 5.7.0 to rubygems

**Comment by francesco-loreti** [comment]
The Rails 6.0.0 beta2 was just released but this gem not support it
```
spec.add_runtime_dependency 'actionpack', '>= 5.0.0.1', '<= 6.0.0.beta1'
spec.add_runtime_dependency 'activesupport', '>= 5.0.0.1', '<= 6.0.0.beta1'
```
