### ISSUE TITLE
replace "/" with "-" before route parameter? 

### ISSUE THREAD

**Issue by setoelkahfi** [enriclluelles/route_translator#190]
Really cool gem, thanks so much 👍 

Is it possible to replace the "/" with "-" before the route paratmeter?

I want to produce these kind or urls:
`domain.com/product-detail-343`
`domain.id/detail-produk-343`

I tried this in routes.rb
   `get 'product_detail:slug', to: 'product#detail', as: :product_detail`
and in each locales yml file:
 `product_detail: product-detail-`

and it doesn't work. It works however, if i puth / before the `:slug`

**Comment by narender2031** [comment]
same issue.

**Comment by tagliala** [comment]
@setoelkahfi @narender2031 

Sorry for this very late reply.

Ultimately, I'm not working on Rails and I'm just keeping this gem up-to-date in my free time. Time is a limited resource, I need space for my personal life and well, stuff like that.

Please try this one:

### routes.rb
```rb
  localized do
    resources :products
    get :product_detail, to: 'products#show'
  end
```

### en.yml
```yml
en:
  hello: "Hello world"
  routes:
    product_detail: 'product-detail-:id'
```

Helper: `product_detail_path(product)`

Let's say, for product 3, url: `/product-detail-3`

Let me know

**Comment by narender2031** [comment]
Thank you @tagliala for your reply. It works for me. 
I am using I18n for locales. so in the case of `de` there is prefix added de when translated route generated. can I remove this prefix during the route translation?

**Comment by tagliala** [comment]
> I am using I18n for locales. so in the case of de there is prefix added de when translated route generated. can I remove this prefix during the route translation?

Could you please clarify this?

**Comment by narender2031** [comment]
`cars_es GET    /es/coches(.:format)            cars#index {:locale=>"es"}`

in this case, can I remove the prefix `es`?

**Comment by narender2031** [comment]
I found the solution. 
`config. hide_locale  = true`

Thanks for your help @tagliala  👍

**Comment by tagliala** [comment]
I think I've answered this question here: https://github.com/enriclluelles/route_translator/issues/190#issuecomment-490434278 so I will close this thread
