### ISSUE TITLE
url_for not working with string locale 

### ISSUE THREAD

**Issue by narender2031** [enriclluelles/route_translator#202]
`url_for(controller: '...', action: '...', locale: '...', only_path: true)`
I am facing the issue. I wan to generate my URLs but does not returns me translated routes.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Route Translator community.

Could you please provide more details?

I need:

1. Version of Ruby
2. Version of Rails
3. Version of route_translator
4. Relevant `routes.rb` part
5. Relevant ruby code from your controllers / views /helpers
6. What you expect to see
7. What you actually see

**Comment by narender2031** [comment]
@tagliala Thanks for the quick reply. 
`ruby '2.5.0'`
`route_translator (5.10.0)`
routes.rb
```
        localized do
          get :price_XXXXX, to: 'home#price_XXXX'
        end
```

I would like to translate my Url on the change of locale. 
```
  <%= link_to t('pulse.language.english'), url_for(controller: controller.controller_name, action: controller.action_name, locale: 'en', only_path: true), class: 'dropdown-item' %>
    <%= link_to t('pulse.language.german'), url_for(controller: controller.controller_name, action: controller.action_name, locale: 'de'), class: 'dropdown-item' %>
```

expected result: 
en: `/en/price_xxx`
de: `/de/preisvergleich`

got 
en: `/en/preisvergleich`
de: `/preisvergleich`

**Comment by tagliala** [comment]
Hi, could you please add `en.yml` and `de.yml` ?

**Comment by narender2031** [comment]
routes:
en.yml
```
    price_comparison: price-comparison
```
de.yml
```
  price_comparison: preisvergleich
```

**Comment by tagliala** [comment]
Hi, I've prepared a bug report template: https://github.com/enriclluelles/route_translator/issues/new?assignees=&labels=&template=bug_report.md&title=

Please do not omit relevant information (i.e: the path of the translation property: is it placed under the proper translation scope?) and do not censor relevant code (eg: price_xxxx, how it is related to price_comparison?).

If you need to censor relevant code, please change all the words and submit a working example

Closing here

**Comment by narender2031** [comment]
routes.rb

        localized do
          get :price, to: 'home#price'
        end
I would like to translate my Url on the change of locale.

  <%= link_to t('pulse.language.english'), url_for(controller: controller.controller_name, action: controller.action_name, locale: 'en', only_path: true), class: 'dropdown-item' %>
    <%= link_to t('pulse.language.german'), url_for(controller: controller.controller_name, action: controller.action_name, locale: 'de'), class: 'dropdown-item' %>
expected result:
en: /en/price
de: /de/preisvergleich

got
en: /en/preisvergleich
de: /preisvergleich

I want to generate translated URL specific to locale

  routes:
en.yml
```
    price: price
```
de.yml
```
  price: preisvergleich
```



I want to generate URLs following: 
en: /en/price
de: /de/preisvergleich

**Comment by tagliala** [comment]
If you want to get this

> en: /en/price
> de: /de/preisvergleich

with this

```erb
<%= link_to t('pulse.language.english'), url_for(controller: controller.controller_name, action: controller.action_name, locale: 'en', only_path: true), class: 'dropdown-item' %>
<%= link_to t('pulse.language.german'), url_for(controller: controller.controller_name, action: controller.action_name, locale: 'de'), class: 'dropdown-item' %>
```

I should assume that

1. the controller is `home`
2. the action is `price`

So, you should be on the same page and you want to generate localized versions of the current page.

If this is the case, the following wiki can help you: https://github.com/enriclluelles/route_translator/wiki/Generating-translated-URLs

I should also assume that

```
    price: price
```

and

```
  price: preisvergleich
```

are placed under

```
en:
  routes:
    price: price
```

and

```
de:
  routes:
    price: preisvergleich
```

as per Readme: https://github.com/enriclluelles/route_translator#quick-start

This is still not enough, because you will have:

```
$ rails routes | grep home#price
                 price_de GET    /de/preisvergleich(.:format)           home#price {:locale=>"de"}
                 price_en GET    /price(.:format)                       home#price {:locale=>"en"}
```

and this is still not you want, so you also need the following initializer:

```rb
 $ rails routes | grep home#price
                 price_de GET    /de/preisvergleich(.:format)           home#price {:locale=>"de"}
                 price_en GET    /en/price(.:format)                    home#price {:locale=>"en"}

```

as per readme: https://github.com/enriclluelles/route_translator#available-configurations

Hope it helps

**Comment by tagliala** [comment]
Attaching screenshot
![image](https://user-images.githubusercontent.com/556268/65836984-3a9feb00-e2f3-11e9-8673-222c4616757d.png)

**Comment by narender2031** [comment]
rails version: `gem 'rails', '~> 5.1.4'`

initializer/route_translator.rb
```
RouteTranslator.config do |config|
  config.hide_locale = true
end
```
routes.rb
```
 constraints subdomain: Rails.application.config.x.pulse.subdomain do
  scope module: 'demo', as: 'demo' do
      scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/, defaults: defaults do
          localized do
             get :price, to: 'home#price'
          end
      end
  end
end
```

rails routes 
```
 demo_price_de GET    (/:locale)/preisvergleich(.:format) demo/home#price {:subdomain=>"demo", :locale=>"de"}
demo_price_en GET      (/:locale)/price(.:format) demo/home#price 
{:subdomain=>"demo", :locale=>"en"}

```

Views: 
```
<%= link_to t('demo.language.english'), url_for(controller: controller.controller_name, action: controller.action_name, locale: 'en', only_path: true), class: 'dropdown-item' %>
<%= link_to t('demo.language.german'), url_for(controller: controller.controller_name, action: controller.action_name, locale: 'de'), class: 'dropdown-item' %>
```

expected results: 

en: `/en/price`
de: `de/preisvergleich `

but got: 

en: `/en/preisvergleich`
de: `de/preisvergleich`

Also tried in the console:- 

I already tried with urf_for helper method in the console 

1. `include Rails.application.routes.url_helpers`
```
2.5.0 :002 > url_for controller: :home, action: :price, locale: 'en', only_path: true
Traceback (most recent call last):
        1: from (irb):2
ActionController::UrlGenerationError (No route matches {:action=>"price", :controller=>"home", :locale=>"en"})
```

**Comment by tagliala** [comment]
Hi,

just a mistake on my side, wrong copy and paste

Initializier:

```rb
RouteTranslator.config do |config|
  config.force_locale = true
end
```


then:

please remove the :scope with locale, it will complicate the design. 

Routes should look like:

```rb
Rails.application.routes.draw do
  localized do
    get :price, to: 'home#price'
  end
end
``

**Comment by narender2031** [comment]
thanks @tagliala
