### ISSUE TITLE
Incompatible with Rails 6.1

### ISSUE THREAD

**Issue by sedubois** [enriclluelles/route_translator#209]
### Steps to reproduce

Run bundle with this Gemfile:
```rb
gem 'rails', github: 'rails/rails'
gem 'route_translator'
```

### Expected behavior

Route translator should be compatible with Rails >= 6.1. I am currently using Rails 6.0.2.2 but need to try new ActiveStorage features only available on Rails master (6.1.0-alpha). This is both to improve my app and possibly to submit contributions to the Rails repo.

### Actual behavior

Bundle install fails.

### System configuration
**Rails version**: Rails master (6.1.0-alpha)
**Ruby version**: 2.6.6
**Route Translator version**: 7.1.2

### I18n configuration

```rb
Rails.application.config.i18n.available_locales = [:en, :fr]
```

### Route Translator initializier

Source of: `config/initializers/route_translator.rb`

```rb
RouteTranslator.config do |config|
  config.locale_param_key = :path_locale
end
```

**Comment by tagliala** [comment]
Closing here.

Rails 6.1 compatible branch: `rails-edge`
