### ISSUE TITLE
routes translator and mailer url issue undefined method `localized' for #<ActionDispatch::Routing::Mapper

### ISSUE THREAD

**Issue by ronval** [enriclluelles/route_translator#219]
Hi guys i'm having some trouble getting this gem to work with rails mailer.
### Steps to reproduce*
I added the localized block to the routes I wanted to translate. I added the translation files for english and spanish (en.rb and es.rb ) Submitted a request for password recovery which sends a simple email with token etc etc to reset password. Very simple and it worked fine before I added the localized block. 

### Expected behavior*
It should send me an email  with the password recovery link. Where I can then click a link inside the email to reset Password.

### Actual behavior*
I get an error saying 

NoMethodError: undefined method `localized' for #<ActionDispatch::Routing::Mapper:0x00007f9ef5f2f080>

and 

ActionView::Template::Error: undefined method `new_password_url' for #<#<Class:0x00007f9efb878920>:0x00007f9ef9aad800>

But When I remove the localized block the emails are sent like normal and I can click on the url inside the email just fine. Am I missing something here? It seems like the gem isn't playing nice with the ActionDispatch  and mailer or something?  Any help would be appreciated. Thanks guys

### System configuration*
**Rails version**:
Rails 6.0.2.1
**Ruby version**:
ruby '2.5.3'
**Route Translator version**:
 route_translator (8.0.0)

### I18n configuration*

```rb
    config.i18n.load_path += Dir[Rails.root.join('config', 'locales', '**', '*.{rb,yml}')]
    config.i18n.available_locales = [:es, :en, :pt]
    config.i18n.default_locale = :es
```

### Route Translator initializier

Source of: `config/initializers/route_translator.rb`

```rb
RouteTranslator.config do |config|
  config.force_locale = true
  
end
```

### Source code of routes.rb*

Source of: `config/routes.rb`

```rb
localized do 
 get "register"=> "users#new", :as=> :new_user
 get "login" => "sessions#new", :as=> :login
 get "password_recovery" => "password_recovery#new", :as=> :password_recovery

end 
```

### Locale `.rb` files*

Source of `config/locales/en.rb`

```rb
{ en: {
        routes:{
                 
                  register: "register",
                  login: "login",
                  password_recovery:"password_recovery",
                  new_password:"new_password"
                } 
      }
}

```

Source of `config/locales/es.rb`

```rb
{ es: {
        routes:{
                  
                  register: "registrar",
                  login: "iniciar_sesion",
                  password_recovery:"recupera_mi_contraseña",
                  new_password:"nueva_contraseña"
                } 
      }
}



```

### Output of `rails routes`*

Result of `bundle exec rails routes`:

```
new_user_en GET    /en(/:locale)/register(.:format)       users#new {:locale=>"en"}
new_user_pt GET    /pt(/:locale)/register(.:format)        users#new {:locale=>"pt"}
new_user_es GET    /es(/:locale)/registrar(.:format)      users#new {:locale=>"es"}
login_en GET    /en(/:locale)/login(.:format)            sessions#new {:locale=>"en"}
login_pt GET    /pt(/:locale)/login(.:format)           sessions#new {:locale=>"pt"}
login_es GET    /es(/:locale)/iniciar_sesion(.:format)   sessions#new {:locale=>"es"}
password_recovery_en GET    /en(/:locale)/password_recovery(.:format)     password_recovery#new {:locale=>"en"}
password_recovery_pt GET    /pt(/:locale)/password_recovery(.:format)       password_recovery#new {:locale=>"pt"}
password_recovery_es GET   /es(/:locale)/recupera_mi_contrase%C3%B1a(.:format) password_recovery#new{:locale=>"es"}
new_password GET    (/:locale)/new_password(.:format)   password_recovery#new_password {:locale=>/en|es|pt/}

```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Route Translator community and for this detailed report.

Who is sending emails? Is it possible that this is done in a separate process (sidekiq) that has not been restarted?

**Comment by ronval** [comment]
That fixed it i'm such a moron, I didnt think to restart the redis and sidekiq server. Sorry for wasting your time with this. At least we have a record if people google this lol. Appreciate your help on this thanks :)

**Comment by tagliala** [comment]
@ronval you're welcome and don't worry, glad you solved

Closing here
