### ISSUE TITLE
Routes not found error after upgrading to Rails 6.0 from Rails 5.1

### ISSUE THREAD

**Issue by mubarik** [enriclluelles/route_translator#243]
Hi ,

Route translator not working after upgrading from Rails 5.1 to Rails 6.0. We are getting routes not found error for the routes in localized block. If we remove those routes from localized block they start working. I checked Rake routes and i can see the routes registered in Journey Routes.

**Comment by tagliala** [comment]
Hi, please fill in the bug report: https://github.com/enriclluelles/route_translator/issues/new?assignees=&labels=&template=bug_report.md&title=

A repo with a reproducible test case would help in debugging this issue

**Comment by tagliala** [comment]
...but before, I think this also includes an upgrade from Route Translator 6 to >= 7.0

From the changelog of Route Translator 7:
```
[FEATURE] Do not set locale from url by default
```

And the readme does not contain the proper instructions for 7.0, so please check that your application controller (or the controller you want to translate) contains `around_action set_locale_from_url`

**Comment by mubarik** [comment]
Thank you. Issue is resolved. I was upgraded to route_translator 10 . By shifting back to route_translator 7.0. It resolved the issue

**Comment by tagliala** [comment]
> I was upgraded to route_translator 10 . By shifting back to route_translator 7.0. It resolved the issue

Hi, actually your application should be able to use route_translator 10 without issues. The second breaking change that you can read about in https://github.com/enriclluelles/route_translator/blob/master/UPGRADING.md is related to the `host` configuration

Downgrading to 7.0, which include the breaking change, is just a workaround

Anyway, I can't help without a proper report and a reproducible test case
