### ISSUE TITLE
Unable to translate routes with custom param

### ISSUE THREAD

**Issue by r-obeen** [enriclluelles/route_translator#247]
Hey, I've been searching for 2 hours now, I even browsed the whole Issues tab, I couldn't find a solution.

---

### System configuration*
**Rails version**:
Rails 6.1.3.1
**Ruby version**:
ruby 2.5.7p206
**Route Translator version**:
route_translator (10.0.0)

### I18n configuration*
```
config.i18n.default_locale = :fr
config.i18n.available_locales = [:en, :fr]
config.i18n.fallbacks = true
I18n.t :missing, :default => 'No translation available.'
```

### Route Translator initializier
```
RouteTranslator.config do |config|
  config.force_locale = false
end
```

---

Soooo, here are my routes :
```
scope "(:locale)", locale: /fr|en/ do 
  localized do
    namespace :new_blog do
      get '', action: 'index', as: '/'
      
      get 'posts'
      
      get 'post/:uid', action: 'post', as: :post
    end
  end
end
```

Now, I'm struggling to translate the routes that have `/:uid` as parameter. How should it be done ?

Here is my `en.yml` :
```
en:
  routes:
    new_blog: new_blog
    posts: vacation
    post: vacation
```

And the `fr.yml`
```
fr:
  routes:
    new_blog: new_blog
    posts: sejour
    post: sejour
```

The `get 'posts'` get translated perfectly into
- FR (default language) : `/new_blog/sejour`
- EN : `/en/new_blog/vacation`

But then, for the `get: 'post/:uid`, the routes are weird :
- FR (default language) : `/fr/new_blog/sejour/la-montagne-pelee` (i'm not supposed to have `fr` as it's the default language
- EN : `/en/en/new_blog/vacation/carnival-in-martinique` (I'm not supposed to have `/en` twice

Anyone know how I should do it ?

note : I'm using `rails-i18n` as well for my app.

Thanks in advance !

**Comment by tagliala** [comment]
Hi,

The `scope` block is not required. If you need that scope for other routes, just move the `localized` block outside. Please remove it and let me know.

> i'm not supposed to have fr as it's the default language

If you use scope, `fr` will be there

Please also remove `config.force_locale = false` setting, since it's a default.

**Comment by r-obeen** [comment]
> Hi,
> 
> The `scope` block is not required. If you need that scope for other routes, just move the `localized` block outside. Please remove it and let me know.
> 
> > i'm not supposed to have fr as it's the default language
> 
> If you use scope, `fr` will be there
> 
> Please also remove `config.force_locale = false` setting, since it's a default.

That was exactly it. Thank you

**Comment by tagliala** [comment]
Welcome. Can I close here?

**Comment by r-obeen** [comment]
Sure, go ahead.

**Comment by r-obeen** [comment]
@tagliala Okay actually... I have a question.

I would like to generate my routes specifying the locale as param :
`new_blog_post_path(uid:uid, locale:lang)` something like this... But it's not working.

Any idea ?

**Comment by tagliala** [comment]
Is `locale` variable a string rather than a symbol?

Ref: https://github.com/enriclluelles/route_translator#changing-the-language

**Comment by r-obeen** [comment]
@tagliala It's a string. Thank you for your quick replies by the way, much appreciated !
