### ISSUE TITLE
Bump version rubygems for Rails 7 support

### ISSUE THREAD

**Issue by navidemad** [enriclluelles/route_translator#256]
Hello,

Thanks again for your awesome gem.

Could you push the new version with the commit : [Allow Rails 7.0 ](https://github.com/enriclluelles/route_translator/commit/42055c73dbba2b4668c15a3d0385cb0d500c4186) into rubygems.

Otherwise we have to reference the github main in our Gem if we are running with Rails 7.0.0

**Comment by tagliala** [comment]
Thanks for the heads-up, I've prepared everything in anticipation for Rails 7 and then I forgot to release

12.1.0 released
