### ISSUE TITLE
Question: "/" path locale always English

### ISSUE THREAD

**Issue by pglombardo** [enriclluelles/route_translator#278]
On this [open source application](https://github.com/pglombardo/PasswordPusher) that I maintain (using route_translator) I have localised routes without the use of HTTP Accept headers.  

All works great with the exception of the _unlocalised root_ `/` path.  I always get English strings despite the default locale being something else.

![Screenshot 2023-02-16 at 12 13 45](https://user-images.githubusercontent.com/395132/219353259-b305ffd9-b442-475b-8088-f76c027375bf.png)

Here is the setup:

**config/initializers/route_translator.rb**
```ruby
RouteTranslator.config do |config|
  config.force_locale = true
  config.generate_unnamed_unlocalized_routes = true
end
```

**config/routes.rb**

```ruby
    localised do
        root to: 'passwords#new'
    end
    root to: 'passwords#new', locale: I18n.default_locale
```

**rails routes**

```ruby
$> PWP__DEFAULT_LOCALE=de rails routes | grep root
root_sr GET    /sr    passwords#new {:locale=>"sr"}
root_sv GET    /sv    passwords#new {:locale=>"sv"}
root_zh_cn GET    /zh-cn    passwords#new {:locale=>"zh-CN"}
root_de GET    /de    passwords#new {:locale=>"de"}
root GET    /    passwords#new {:locale=>:de}
```

`PWP__DEFAULT_LOCALE` is an application specific environment variable that gets translated into:

```ruby
I18n.default_locale = Settings.default_locale ? Settings.default_locale : 'en'
```

Something is off and I'm looking for a pointer as to what could be the root cause.  Any ideas?

**Comment by tagliala** [comment]
Ciao!

```
root GET    /    passwords#new {:locale=>:de}
                                         ^^^
```

Can you please try to pass the locale as a string?

```diff
- root to: 'passwords#new', locale: I18n.default_locale
+ root to: 'passwords#new', locale: I18n.default_locale.to_s
```

This is a limitation in route translator: https://github.com/enriclluelles/route_translator#changing-the-language 

I'm not sure that this will fix, let me know

**Comment by pglombardo** [comment]
Good eye but no change unfortunately.

What is the best practice for `/`?  How should this be setup?

I'm one step away from just doing a hard path match and redirect to the default locale but seems hacky.

**Comment by pglombardo** [comment]
I think I have a fix that I _believe_ may be the solution.  Filing this issue seems to have helped :-)

in `application_controller.rb` I customise the `around_action` [set_locale_from_url](https://github.com/enriclluelles/route_translator/blob/2dd4afcc81310cf271ad5d9cdc20d7dc3318c3b6/lib/route_translator/extensions/action_controller.rb#L11):

```ruby
around_action :custom_set_locale_from_url

def custom_set_locale_from_url
  locale_from_url = RouteTranslator.locale_from_params(params) || 
                            RouteTranslator::Host.locale_from_host(request.host) || 
                            I18n.default_locale # Add this option as a final fallback
  if locale_from_url
    old_locale  = I18n.locale
    I18n.locale = locale_from_url
  end

  yield
ensure
  I18n.locale = old_locale if locale_from_url
end
```

It seems to work but I need to test for a while.

Any other input/ideas are appreciated!

**Comment by tagliala** [comment]
I understand that the application experiencing the issue is open source, but can you please provide a reduced test case?

Please just add the minimum code to reproduce this issue starting from this commit: https://github.com/diowa/ruby3-rails7-bootstrap-heroku/tree/f26a4db9fd8150923eaed9610ea418bbcec8e0f3

**Comment by pglombardo** [comment]
That's a big ask @tagliala.  I'm not reporting a bug - just advice & experience from the community.

If my current solution doesn't work out - I'll definitely put together a reproduce case.

Thanks for looking!

**Comment by tagliala** [comment]
Can you please try to put the unlocalized root path above the localized block?

```
    root to: 'passwords#new', locale: I18n.default_locale
    localised do
        root to: 'passwords#new'
    end
```

Please also check for side effects

**Comment by pglombardo** [comment]
Hi @tagliala - The work-around I posted in [this comment](https://github.com/enriclluelles/route_translator/issues/278#issuecomment-1433003779) resolved the issue for my project.

The final [route.rb](https://github.com/pglombardo/PasswordPusher/blob/master/config/routes.rb#L73) setup is simply:

```ruby
localised do
    root to: 'passwords#new'
end
```

Great tool you have here.  I use it in combo with [translation.io](https://translation.io) (which is free for OSS) and we're up to 19 languages.  Thanks the help!  I'll close out this issue.
