### ISSUE TITLE
undefined method `eager_load!' for RouteTranslator:Module (NoMethodError)

### ISSUE THREAD

**Issue by Rozan-Mustafa** [enriclluelles/route_translator#296]
ruby 3.2.2
rails 7.0.7

route_translator v14.0.0

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Route Translator Community.

Debugging Route Translator issues is a time consuming task, please use a web browser to fill out our [Bug Report](https://github.com/enriclluelles/route_translator/issues/new?assignees=&labels=bug%2Cneeds-triage&projects=&template=bug_report.yml&title=Bug%3A+) template and provide as many information as you can.

For this specific report, it would be much better to include a reproducible test case.

**Comment by navidemad** [comment]
@tagliala 

Hello, firstly thanks for your gem it helps us a lot.

I got the same issue, we downgraded to < 14 for the moment.
I tried to make a reproducible case, but i didn't isolate the issue but it appears only in my CI, not when i'm running the test locally on my computer.

```ruby
Run bin/rspec spec'

An error occurred while loading ./spec/components/back_link_component_spec.rb.
Failure/Error: require_relative "../config/environment"

NoMethodError:
  undefined method `eager_load!' for RouteTranslator:Module
./vendor/bundle/ruby/3.2.0/gems/railties-7.0.7.2/lib/rails/application/finisher.rb:75:in `each'
./vendor/bundle/ruby/3.2.0/gems/railties-7.0.7.2/lib/rails/application/finisher.rb:75:in `block in <module:Finisher>'
./vendor/bundle/ruby/3.2.0/gems/railties-7.0.7.2/lib/rails/initializable.rb:32:in `instance_exec'
./vendor/bundle/ruby/3.2.0/gems/railties-7.0.7.2/lib/rails/initializable.rb:32:in `run'
./vendor/bundle/ruby/3.2.0/gems/railties-7.0.7.2/lib/rails/initializable.rb:61:in `block in run_initializers'
./vendor/bundle/ruby/3.2.0/gems/railties-7.0.7.2/lib/rails/initializable.rb:60:in `run_initializers'
./vendor/bundle/ruby/3.2.0/gems/railties-7.0.7.2/lib/rails/application.rb:372:in `initialize!'
./config/environment.rb:7:in `<top (required)>'
./spec/rails_helper.rb:5:in `require_relative'
./spec/rails_helper.rb:5:in `<top (required)>'
./spec/models/user_spec.rb:3:in `<top (required)>'
```

I do not have any matches for **eager_load!** in my project and neither in the gem when i opened it through `bundle open route_translator`

**Comment by tagliala** [comment]
> I got the same issue, we downgraded to < 14 for the moment.

Does it work with < 14?

**Comment by tagliala** [comment]
I think I got the issue

**Comment by tagliala** [comment]
@navidemad replicated thanks, working on a fix

**Comment by navidemad** [comment]
> > I got the same issue, we downgraded to < 14 for the moment.
> 
> Does it work with < 14?
> 
> Ok. If it works on localhost but does not work on CI, there could be some issues with the bundled gems there

Yes i confirm you, it happened only after we upgraded with your latest update.

**Comment by tagliala** [comment]
14.0.1 released, sorry for the small inconvenience

**Comment by navidemad** [comment]
Thanks for the patch, i tried the main branch version, and it's works perfectly 💯
