### ISSUE TITLE
Dynamic default locale

### ISSUE THREAD

**Issue by quovai** [enriclluelles/route_translator#312]
### Issue: Dynamic Default Locales for Multiple Virtual Hosts

**Context:**

We are operating a platform that serves multiple portals, each with its own virtual host and default locale. The requirement is to dynamically adjust the URL structure based on the portal’s default language:

- **Portal A:**
  - **Default Locale:** Italian (IT)
  - **URL Structure:**
    - IT (default): `www.portalA.com` (no `/it` segment for default language)
    - EN: `www.portalA.com/en`

- **Portal B:**
  - **Default Locale:** English (EN)
  - **URL Structure:**
    - EN (default): `www.portalB.com` (no `/en` segment for default language)
    - IT: `www.portalB.com/it`

**Problem:**

Depending on the portal being accessed, the language segment should be omitted from the URL when generating paths for the default locale. For non-default locales, the language segment should be included. We have tried various configurations and approaches but have not been successful in achieving this dynamic behavior.

**Question:**

Is it possible to configure our platform to handle multiple dynamic default locales, where the language segment is only included for non-default languages, depending on the virtual host? If so, what would be the recommended approach to implement this?

**Example Scenarios:**

- **Portal A:**
  - IT: `www.portalA.com/section/page`
  - EN: `www.portalA.com/en/section/page`

- **Portal B:**
  - EN: `www.portalB.com/section/page`
  - IT: `www.portalB.com/it/section/page`

**Comment by quovai** [comment]
P.S We've tried with `locale_segment_proc` but it seems not to be evaluated at runtime, only at route generation time.

**Comment by tagliala** [comment]
Hi,

This use case is not supported

Ref: https://github.com/enriclluelles/route_translator/issues/288#issuecomment-1666464135

There is a wiki for that
