### ISSUE TITLE
NoMethodError: undefined method `optimize_routes_generation?'

### ISSUE THREAD

**Issue by stayhero** [enriclluelles/route_translator#51]
Hey.

Today I upgraded our Rails 4 (4.0.3, Ruby 2.1.0) application to use route_translator 3.2.0 instead of 3.1.0. Since upgrading a lot of our tests are failing (in some kind of a weird way). I'm seeing errors like this:

```
ActionMailer::TestCase#test_track_path:
NoMethodError: undefined method `optimize_routes_generation?' for #<ActionMailer::TestCase:0x007fedc9958cd8>
```

When I downgrade back to 3.1.0. everything works again. 

I was able to find out what caused the error: Our routes file looks like this: 

``` ruby
MyApp::Application.routes.draw do
  # Routing for localized outer content section
  localized do
    root to: 'index#index'
    get 'benefits' => 'index#benefits', as: :index_benefits
    get 'how-it-works' => 'index#how_it_works', as: :index_how_it_works
    get 'pricing' => 'index#pricing', as: :index_pricing
  end

  get   '/test/track'         => 'index#test_track', as: :test_track

  # A lot of more routes ....
end
```

When I rename the route for /test/track to e.g. :test_foo is still fails, when I rename it to :track_test e.g. the error disappears. So any route with a name starting with **test** causes this error.

I was not yet able to dig into the route_translator code or to build a proper failing test. Maybe anyone has already an idea what introduced this behaviour in version 3.2.0?

**Comment by MarcelEeken** [comment]
This bug is reintroduced in v4.1.0 with PR #45

**Comment by tagliala** [comment]
PR are very welcome
