### ISSUE TITLE
app.new_user_session_path(locale: I18n.locale) should read "/es/users/sign_in", not "/users/sign_in?locale=es"

### ISSUE THREAD

**Issue by tute** [enriclluelles/route_translator#6]
Like your gem, and finding many issues while implementing it. How can we make `app.new_user_session_path(locale: I18n.locale)` generate `/es/users/sign_in` instead of `/users/sign_in?locale=es`?

Thank you again.

**Comment by Senjai** [comment]
@enriclluelles What was the result of your investigation?

**Comment by air720boarder** [comment]
+1

**Comment by tagliala** [comment]
Hi, please do not +1 here

I don't know why this is closed but please open a new request explaining what is happening and providing a failing test case (or a minimal application hosted on github).

Then I will add a "help wanted" label.

PR are welcomed
