### ISSUE TITLE
problem with routes like '...(/p:p)'

### ISSUE THREAD

**Issue by maozzz** [enriclluelles/route_translator#76]
That's my error:

Uncaught exception: 
parse error on value "$" ($end)
	/home/maoz/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/racc/parser.rb:529:in `on_error'
	/home/maoz/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/racc/parser.rb:258:in ...

And that's problematic rout:
get '/photographers/favorite(/p:p)' => 'photographers#favorite', :as => 'favorite_photographers'

Such construction works:
get '/photographers/favorite(/p(:p))' or get '/photographers/favorite(/:p)'

**Comment by tagliala** [comment]
Closing here, let me know if this is still an issue
