### ISSUE TITLE
Problems with routing mapper (rails 4.2 beta4) can't start server

### ISSUE THREAD

**Issue by MathijsK93** [enriclluelles/route_translator#77]
After installing the route_translator gem, i can't start my server.

Getting this error:

```
/Users/Mathijs/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.2.0.beta4/lib/action_dispatch/routing/mapper.rb:81:in `initialize': wrong number of arguments (4 for 6) (ArgumentError)
```

Using ruby 2.1.5

Anyone suggestions?

**Comment by paulslaby** [comment]
Why this version is not here? https://github.com/enriclluelles/route_translator/releases
(I mean "How it works?" not "Do it")

**Comment by enriclluelles** [comment]
That probably is because I haven't tagged it. Didn't even know that releases were auto-created until you pointed that out. I will add the tag when I get on a computer. Do you use the gem in zipped format?

**Comment by paulslaby** [comment]
No, I don't. I install it through rubygems, but I had older version installed and misread your post about release and wondered it did not work.
