### ISSUE TITLE
is it possible to deactivate not necessary routes ?

### ISSUE THREAD

**Issue by bulleric** [enriclluelles/route_translator#78]
Hey thanks for this awesome gem ;) 

Is it possible to deactivate not necessary routes.
Currently my app generate for every language the final routes. But i really need only 2 of them.

Thx for help

Best regards 

Eric

**Comment by 14113** [comment]
:+1:

**Comment by astjohn** [comment]
In my case, we are unable to specify available locales for our entire rails stack, but still only want to translate a few locales for our routes. I made this pull request (https://github.com/enriclluelles/route_translator/pull/90) to handle it. Check it out and let me know if it works out for you:

**Comment by tagliala** [comment]
Closing here
