### ISSUE TITLE
Problem with rspec and format parameter

### ISSUE THREAD

**Issue by mkon** [enriclluelles/route_translator#81]
Hello,

I am running into a weird problem when using your gem.

I have a controller spec, and I am writing a test like this:

```
      it "works" do
        post :create, locale: :en, format: :js
        expect(response).to be_success
      end
```

But I will get a ActionController::UrlGenerationError. If I leave the format parameter out, it will work however. The test will also work if I move the resource out of the localize block in the routes file. I was able to reproduce this with one test in a fork to make this easier to show what the issue is:

https://github.com/mkon/route_translator/commit/ad4f7adc11387c630894589dd20acba960574c64

Test will fail with 

```
ActionController::UrlGenerationError: No route matches {:action=>"index", :controller=>"products", :format=>:json, :locale=>:es}
    /Users/konstantin/.rvm/gems/ruby-2.1.3/gems/actionpack-4.2.0.beta1/lib/action_dispatch/journey/formatter.rb:45:in `generate'
    /Users/konstantin/.rvm/gems/ruby-2.1.3/gems/actionpack-4.2.0.beta1/lib/action_dispatch/routing/route_set.rb:658:in `generate'
    /Users/konstantin/.rvm/gems/ruby-2.1.3/gems/actionpack-4.2.0.beta1/lib/action_dispatch/routing/route_set.rb:689:in `generate'
    /Users/konstantin/.rvm/gems/ruby-2.1.3/gems/actionpack-4.2.0.beta1/lib/action_dispatch/routing/route_set.rb:684:in `generate_extras'
    /Users/konstantin/.rvm/gems/ruby-2.1.3/gems/actionpack-4.2.0.beta1/lib/action_dispatch/routing/route_set.rb:679:in `extra_keys'
    /Users/konstantin/.rvm/gems/ruby-2.1.3/gems/actionpack-4.2.0.beta1/lib/action_controller/test_case.rb:204:in `assign_parameters'
    /Users/konstantin/.rvm/gems/ruby-2.1.3/gems/actionpack-4.2.0.beta1/lib/action_controller/test_case.rb:615:in `process'
    /Users/konstantin/.rvm/gems/ruby-2.1.3/gems/actionpack-4.2.0.beta1/lib/action_controller/test_case.rb:64:in `process'
    /Users/konstantin/.rvm/gems/ruby-2.1.3/gems/actionpack-4.2.0.beta1/lib/action_controller/test_case.rb:504:in `get'
    /Users/konstantin/Rails/Gems/route_translator/test/routing_test.rb:590:in `test_tests_can_find_routes_with_format'
```

Again if the format parameter is removed, the test will pass. The test will also fail if format: :html is used.

**Comment by dmasur** [comment]
Hi there,

i am running into exactly the same problem.

**Comment by tanguyantoine** [comment]
maybe use 'en' instead of :en

**Comment by mkon** [comment]
You are right that it goes away if locale is a string. Still it seems weird that `get :index, locale: :es, format: :json` fails and requires a string, while `get :index, locale: :es` is working just fine.

**Comment by tagliala** [comment]
Hi,

I was looking at this issue.

Just a little consideration about the format

With rails 4.2.5, the `process` meethod (used by `get`) apparently doesn't allow to specify format: http://api.rubyonrails.org/classes/ActionController/TestCase/Behavior.html#method-i-process

In Rails 5, `process` method changed and it allows to specify a format: https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/test_case.rb#L431

...let's go back to the issue

If you put a resource inside a `localized` block, you are required to provide a `locale` param with a string value.

```rb
localized do
  resources :products, only: :index
end
```

results into this route:

```rb
(byebug) @routes.routes.first.requirements
{:locale=>"ru", :controller=>"products", :action=>"index"}
```

while

```rb
resources :products, only: :index
```

results into:

```
(byebug) @routes.routes.first.requirements
{:controller=>"products", :action=>"index"}
```

So I would say that this is not an issue and you should provide the locale as a string

Let me know if I'm missing something or if I'm wrong

Meanwhile, closing bere
