### ISSUE TITLE
How to get path for given locale?

### ISSUE THREAD

**Issue by jmarceli** [enriclluelles/route_translator#84]
Is it possible and how to do it?
I mean sth. like:
`projects_path(locale: 'en')`
Where:
**project** is the name of the controller
`I18n.locale.to_s` is different than `'en'`

**Comment by musixite** [comment]
Just add _en on your path:
    projects_en_path

instead of
    projects_path

**Comment by jmarceli** [comment]
Thanks, but it turns out that I need dynamic controller name. I ended up with:
`url_for(controller: controller_name, action: action_name, locale: my_locale)`
