### ISSUE TITLE
undefined method `url_options' using Puma on Heroku

### ISSUE THREAD

**Issue by jdurand** [enriclluelles/route_translator#85]
I was using Unicorn for a while without issues and decided to switch to Puma to take advantage of IO threading. I couldn't reproduce this on my development environment.
Here's the stacktrace from New Relic Using [Puma](https://github.com/puma/puma) on Heroku in production.
I have a hunch it might have something to do with threads... not sure though.

I reverted back to using Unicorn for now.

<code>
    ActionView::Template::Error: undefined method `url_options' for #<Module:0x007ff9fc345230>

    …ionpack-4.2.0/lib/action_dispatch/routing/route_set.rb: 271:in `call'
    …ionpack-4.2.0/lib/action_dispatch/routing/route_set.rb: 334:in `block (2 levels) in define_url_helper'
    …te_translator-4.0.0/lib/route_translator/translator.rb:  30:in `block (2 levels) in add_untranslated_helpers_to_controllers_and_views'
                     /app/app/helpers/
    application_helper.rb: 169:in `event_path'
    /app/app/views/app/shared/_content_event.html.haml:3:in `_app_views_app_shared__content_event_html_haml___3287174521702908540_70355826885860'
    ….2.0/gems/actionview-4.2.0/lib/action_view/template.rb: 145:in `block in render'
    …ctivesupport-4.2.0/lib/active_support/notifications.rb: 164:in `block in instrument'
    …4.2.0/lib/active_support/notifications/instrumenter.rb:  20:in `instrument'
    …ctivesupport-4.2.0/lib/active_support/notifications.rb: 164:in `instrument'
    ….2.0/gems/actionview-4.2.0/lib/action_view/template.rb: 333:in `instrument'
    ….2.0/gems/actionview-4.2.0/lib/action_view/template.rb: 143:in `render'
    …iew-4.2.0/lib/action_view/renderer/partial_renderer.rb: 339:in `render_partial'
    …iew-4.2.0/lib/action_view/renderer/partial_renderer.rb: 310:in `block in render'
    …ew-4.2.0/lib/action_view/renderer/abstract_renderer.rb:  39:in `block in instrument'
    …ctivesupport-4.2.0/lib/active_support/notifications.rb: 164:in `block in instrument'
    …4.2.0/lib/active_support/notifications/instrumenter.rb:  20:in `instrument'
    …ctivesupport-4.2.0/lib/active_support/notifications.rb: 164:in `instrument'
    …ew-4.2.0/lib/action_view/renderer/abstract_renderer.rb:  39:in `instrument'
    …iew-4.2.0/lib/action_view/renderer/partial_renderer.rb: 309:in `render'
    …/actionview-4.2.0/lib/action_view/renderer/renderer.rb:  47:in `render_partial'
    …view-4.2.0/lib/action_view/helpers/rendering_helper.rb:  35:in `render'
    …0/gems/haml-4.0.6/lib/haml/helpers/action_view_mods.rb:  10:in `block in render_with_haml'
    …/bundle/ruby/2.2.0/gems/haml-4.0.6/lib/haml/helpers.rb:  89:in `non_haml'
    …0/gems/haml-4.0.6/lib/haml/helpers/action_view_mods.rb:  10:in `render_with_haml'
    /app/app/views/app/events/home.html.haml:7:in `block (3 levels) in _app_views_app_events_home_html_haml__1023603194467757244_70355867632540'
    /app/app/views/app/events/home.html.haml:6:in `each'
    /app/app/views/app/events/home.html.haml:6:in `each_with_index'
    /app/app/views/app/events/home.html.haml:6:in `block (2 levels) in _app_views_app_events_home_html_haml__1023603194467757244_70355867632540'
    …/ruby/2.2.0/gems/draper-1.4.0/lib/draper/delegation.rb:  10:in `each'
    …/ruby/2.2.0/gems/draper-1.4.0/lib/draper/delegation.rb:  10:in `each_with_index'
    …/ruby/2.2.0/gems/draper-1.4.0/lib/draper/delegation.rb:  10:in `each_with_index'
    /app/app/views/app/events/home.html.haml:3:in `block in _app_views_app_events_home_html_haml__1023603194467757244_70355867632540'
    …tionview-4.2.0/lib/action_view/helpers/cache_helper.rb: 190:in `write_fragment_for'
    …tionview-4.2.0/lib/action_view/helpers/cache_helper.rb: 179:in `fragment_for'
    …tionview-4.2.0/lib/action_view/helpers/cache_helper.rb: 115:in `cache'
                 /app/lib/core_ext/
    fragment_cache_helper.rb:  19:in `fragment_cache'
    /app/app/views/app/events/home.html.haml:2:in `_app_views_app_events_home_html_haml__1023603194467757244_70355867632540'
    ….2.0/gems/actionview-4.2.0/lib/action_view/template.rb: 145:in `block in render'
    …ctivesupport-4.2.0/lib/active_support/notifications.rb: 164:in `block in instrument'
    …4.2.0/lib/active_support/notifications/instrumenter.rb:  20:in `instrument'
    …ctivesupport-4.2.0/lib/active_support/notifications.rb: 164:in `instrument'
    ….2.0/gems/actionview-4.2.0/lib/action_view/template.rb: 333:in `instrument'
    ….2.0/gems/actionview-4.2.0/lib/action_view/template.rb: 143:in `render'
    …ew-4.2.0/lib/action_view/renderer/template_renderer.rb:  54:in `block (2 levels) in render_template'
    …ew-4.2.0/lib/action_view/renderer/abstract_renderer.rb:  39:in `block in instrument'
    …ctivesupport-4.2.0/lib/active_support/notifications.rb: 164:in `block in instrument'
    …4.2.0/lib/active_support/notifications/instrumenter.rb:  20:in `instrument'
    …ctivesupport-4.2.0/lib/active_support/notifications.rb: 164:in `instrument'
    …ew-4.2.0/lib/action_view/renderer/abstract_renderer.rb:  39:in `instrument'
    …ew-4.2.0/lib/action_view/renderer/template_renderer.rb:  53:in `block in render_template'
    …ew-4.2.0/lib/action_view/renderer/template_renderer.rb:  61:in `render_with_layout'
    …ew-4.2.0/lib/action_view/renderer/template_renderer.rb:  52:in `render_template'
    …ew-4.2.0/lib/action_view/renderer/template_renderer.rb:  14:in `render'
    …/actionview-4.2.0/lib/action_view/renderer/renderer.rb:  42:in `render_template'
    …/actionview-4.2.0/lib/action_view/renderer/renderer.rb:  23:in `render'
    …2.0/gems/actionview-4.2.0/lib/action_view/rendering.rb: 100:in `_render_template'
    …ionpack-4.2.0/lib/action_controller/metal/streaming.rb: 217:in `_render_template'
    …2.0/gems/actionview-4.2.0/lib/action_view/rendering.rb:  83:in `render_to_body'
    …ionpack-4.2.0/lib/action_controller/metal/rendering.rb:  32:in `render_to_body'
    …ionpack-4.2.0/lib/action_controller/metal/renderers.rb:  37:in `render_to_body'
    …/actionpack-4.2.0/lib/abstract_controller/rendering.rb:  25:in `render'
    …ionpack-4.2.0/lib/action_controller/metal/rendering.rb:  16:in `render'
    …k-4.2.0/lib/action_controller/metal/instrumentation.rb:  41:in `block (2 levels) in render'
    …support-4.2.0/lib/active_support/core_ext/benchmark.rb:  12:in `block in ms'
         /app/vendor/ruby-2.2.0/lib/ruby/2.2.0/
    benchmark.rb: 303:in `realtime'
    …support-4.2.0/lib/active_support/core_ext/benchmark.rb:  12:in `ms'
    …k-4.2.0/lib/action_controller/metal/instrumentation.rb:  41:in `block in render'
    …k-4.2.0/lib/action_controller/metal/instrumentation.rb:  84:in `cleanup_view_runtime'
    …/2.2.0/gems/searchkick-0.8.5/lib/searchkick/logging.rb: 112:in `cleanup_view_runtime'
    …4.2.0/lib/active_record/railties/controller_runtime.rb:  25:in `cleanup_view_runtime'
    …k-4.2.0/lib/action_controller/metal/instrumentation.rb:  40:in `render'
             /app/app/controllers/concerns/
    before_render.rb:  11:in `block in render_with_before_render_action'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 117:in `call'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 117:in `call'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 190:in `block in simple'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb:  92:in `call'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb:  92:in `_run_callbacks'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 734:in `_run_render_callbacks'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb:  81:in `run_callbacks'
             /app/app/controllers/concerns/
    before_render.rb:  10:in `render_with_before_render_action'
    …ack-4.2.0/lib/action_controller/metal/mime_responds.rb: 216:in `respond_to'
              /app/app/controllers/app/
    events_controller.rb:  36:in `home'
    …k-4.2.0/lib/action_controller/metal/implicit_render.rb:   4:in `send_action'
    …/gems/actionpack-4.2.0/lib/abstract_controller/base.rb: 198:in `process_action'
    …ionpack-4.2.0/lib/action_controller/metal/rendering.rb:  10:in `process_action'
    …/actionpack-4.2.0/lib/abstract_controller/callbacks.rb:  20:in `block in process_action'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 117:in `call'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 117:in `call'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 151:in `block in halting_and_conditional'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 151:in `call'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 151:in `block in halting_and_conditional'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 151:in `call'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 151:in `block in halting_and_conditional'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 151:in `call'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 151:in `block in halting_and_conditional'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 169:in `call'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 169:in `block in halting'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 169:in `call'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 169:in `block in halting'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 234:in `call'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 234:in `block in halting'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 169:in `call'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 169:in `block in halting'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 169:in `call'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 169:in `block in halting'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 169:in `call'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 169:in `block in halting'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 169:in `call'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 169:in `block in halting'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 169:in `call'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 169:in `block in halting'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 234:in `call'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 234:in `block in halting'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 169:in `call'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 169:in `block in halting'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 169:in `call'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 169:in `block in halting'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 169:in `call'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 169:in `block in halting'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 308:in `call'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 308:in `block (2 levels) in halting'
    …0/lib/route_translator/extensions/action_controller.rb:  20:in `set_locale_from_url'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 427:in `block in make_lambda'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 307:in `call'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 307:in `block in halting'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 151:in `call'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 151:in `block in halting_and_conditional'
    …ms/activesupport-4.2.0/lib/active_support/callbacks.rb: 169:in `call'
</code>

**Comment by sbull** [comment]
See https://github.com/puma/puma/issues/647

**Comment by jdurand** [comment]
@sbull thanks for linking the issue... thought it was just me going nuts

**Comment by tagliala** [comment]
Closing here too, this is an issue with MRI that should be solved with ruby 2.3.0
