### ISSUE TITLE
Named routes cannot be translated?

### ISSUE THREAD

**Issue by jensb** [enriclluelles/route_translator#86]
Hello,

I am trying out your gem and I am having a hard time understanding how to get routes like 

```
 get 'foo/bar/whatever/:some_param(/:more_param)', to: 'mycontroller#my_non_rest_action'
```

translated. As far as I understand the docs, the REST object name is used for translation, so if you have `resources :products` you can translate "products" in your URLs. But how about non-REST named routes like above, what do I use as lookup key in the locale.yml files?

**Comment by renanmzmendes** [comment]
I believe that if you write something like 

     get 'foo/bar/whatever/:some_param(/:more_param)', to: 'mycontroller#my_non_rest_action', as: :my_non_rest_route

and on the translation files under the `locales` folder you put something like this:

    en:
        routes:
            my_non_rest_route: horray_its_working

everything will work as expected.

**Comment by activist** [comment]
I tried the above, but cannot make it work. 
With the simple route:
```
get 'foo/bar', to: 'mycontroller#my_non_rest_action', as: :my_non_rest_route
```

And yaml file:
```
en:
    routes:
        my_non_rest_route: horray_its_working
```

I get 404 on /horray_its_working, but /foo/bar still works. Have you tested your above example?

**Comment by activist** [comment]
I found a way around which works for me:
```
en:
    routes:
        foo: myfoo
        bar: mybar
```
This enables the translated route /myfoo/mybar which is exactly what I need.

**Comment by jensb** [comment]
Is it possible that '/' as path separator is hardcoded in route_translator? We use 
`ActionDispatch::Routing::SEPARATORS << "-"` to add "-" as a path separator. Does this also work?

**Comment by tagliala** [comment]
Hi,

Sorry but I will not implement support for this use case

Anyway, PR are welcomed
