### ISSUE TITLE
I18n.locale handling breaks as soon as route_translator gem is activated

### ISSUE THREAD

**Issue by GSI** [enriclluelles/route_translator#88]
Vanilla behaviour:
1. Set **I18n.locale** in a controller action
2. Call the according action from within a test
3. After the above call, notice that the **I18n.locale** now equals the one set in the controller action

When adding `gem 'route_translator', '4.0.0'` to Gemfile, the **I18n.locale** is back to default instead (step 3).

I'll add a basic rails project that reproduces the error.

**Comment by GSI** [comment]
Error reproduction in https://github.com/GSI/route_translator-88

**Comment by tagliala** [comment]
Hmm... this should not be an error... `route_translator` runs your controller code inside a block and then restores I18n.locale 

you could skip route_translator in this way
```rb
class StaticController < ApplicationController

  skip_around_action :set_locale_from_url, only: [:unlocalized]

  def unlocalized
    I18n.locale = params[:locale]
  end

end
```

and your test will pass
```
$ rake test
# Running:

.

Finished in 0.072595s, 13.7751 runs/s, 27.5501 assertions/s.
```

**But...** I advise you to use `around_action` for your purposes

```rb
class StaticController < ApplicationController

  skip_around_action :set_locale_from_url, only: [:unlocalized]
  around_action :set_locale_from_param, only: [:unlocalized]

  private
  def set_locale_from_param
    I18n.with_locale params[:locale] do
      yield
    end
  end
end
```

Your test will fail, but you will not experience stuff like #44.

**Comment by tagliala** [comment]
Related comments: https://github.com/enriclluelles/route_translator/issues/44#issuecomment-37105648 https://github.com/enriclluelles/route_translator/issues/44#issuecomment-37212297

**Comment by tagliala** [comment]
Closing here
