### ISSUE TITLE
path helper and locale param

### ISSUE THREAD

**Issue by vizo** [enriclluelles/route_translator#96]
`activity_path(@activity, {locale: 'en'})`
gives me path in current language, not in 'en'.

Why is this happening, any idea?

UPDATE:
Ok i checked closed issues and i saw that activity_path without locale suffix is always taking current language. Is this possible to override some how when there is locale param set? 

Rewriting whole application with path_for({controller: ..., action: ...., locale: ....}) would take too much time.

**Comment by tagliala** [comment]
as a workaround, you could use `activity_en_path(@activity)`

I'm using shaming stuff like `send(:"activity_#{locale}_path", @activity)`

**Comment by vizo** [comment]
Thanks for your help.

**Comment by pkuczynski** [comment]
Actually the much simpler way is to use url_for helper:

* ```url_for(locale: @locale, only_path: true)``` - would generate current path in @locale language
* ```url_for(controller: '...', action: '...', locale: @locale, only_path: true)``` - would do it for specified controller's action

**Comment by tagliala** [comment]
https://github.com/enriclluelles/route_translator/wiki/Generating-translated-URLs
