### ISSUE TITLE
Flexible path translation.

### ISSUE THREAD

**Issue by jastix** [enriclluelles/route_translator#97]
In our controllers we have two of them that share the same name, but use different names depending on a context. I would like to make route_translator to choose a translation depending on, for example, a controller's namespace. 

Is there a way to choose which translation to use?

Currently, I see that the gem takes a path, splits it in words and looks up each word separately under `:routes` scope in translations files. 
Providing translation for `:as` part of a route does not achieve what I want to do.

Setup: Rails 4.2, route_translator@master

**Comment by jastix** [comment]
To illustrate my question, I made some changes to the gem code (with a test case): dcce1da3f713e660d38d1b5e66015462e0e6ed93

Now specific translations can be nested under `routes/controllers`. Route_translator checks nested translations first and then translations directly under `routes`.

**Comment by tagliala** [comment]
@jastix do you mind to submit a PR against the develop branch?

**Comment by jastix** [comment]
@tagliala here you go https://github.com/enriclluelles/route_translator/pull/124

**Comment by tagliala** [comment]
This has been implemented in version 5.1.0
